### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by colstrom** [andyw8/codeclimate-engine-rb#4]
Hey Andy,

Thanks for publishing this gem. I'm interested in using it, but there's no license included. If you haven't settled on one, the GitHub team put together a great site to help with that choice at [choosealicense.com](http://choosealicense.com/)!

Without a license, the copyright laws in most countries default to "All Rights Reserved".

Thanks for taking the time to read, and I hope you find a license that fits with the reason you chose to share this code with the world.

**Comment by andyw8** [comment]
Hi @colstrom, I've added the MIT license.

**Comment by colstrom** [comment]
Thanks for the prompt response. Much appreciated!
