### ISSUE TITLE
Licence missing in the rubygems version and in the gemspec

### ISSUE THREAD

**Issue by mensfeld** [andyw8/codeclimate-engine-rb#9]
The "codeclimate-engine-rb" gem seems not to have a license at all. Unless a license that specifies otherwise is included, nobody else can use, copy, distribute, or modify that library without being at risk of take-downs, shake-downs, or litigation.

I know, that this gem has a license on github, however it's missing one at rubygems: https://rubygems.org/gems/codeclimate-engine-rb license => N/A

**Comment by andyw8** [comment]
Hi Macij,

I've release v0.4.1 which now shows the MIT license on rubygems.org:
https://rubygems.org/gems/codeclimate-engine-rb/versions/0.4.1

I'm not sure what connection this has to the method_source gem - I'm not
the author of that.

**Comment by mensfeld** [comment]
Sorry for the name mismatch. I've reported see problem there and copy pasted the error message from coditsu. Thank you!
